//
//  FirstSceneSceneTests.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 10/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import SampleVIPSwift

struct FirstInjectorTest: Injectable {
  static let shared: FirstInjectorTest = FirstInjectorTest()
  private init() {}
}

//use the factory Dependency injection and implement the factorable protocol
extension FirstInjectorTest: FirstFactorable, FirstServicesFactorable {
  
  func makeRouter(viewController: UIViewController?) -> FirstRouting {
    let router = FirstRouter(viewController)
    //custom implementation for this test
    return router
  }
  
}

class FirstSceneTests: XCTestCase {
  
  var vc: FirstViewController<FirstInjectorTest>!
  var customDataSource: FirstModel.DataSource!
  
  override func setUp() {
    
    customDataSource = FirstModel.DataSource(testVariable: 29)
    let customView = FirstView()
    
    vc = FirstViewController(factory: FirstInjectorTest.shared, mainView: customView, dataSource: customDataSource)
  }
  
  override func tearDown() { }
  
  func testCustomInteractorDataSourceShouldChange() {
    
    XCTAssertTrue(customDataSource.testVariable == 29, "Test Variable should be 29")
    
    vc.doSomethingToInteractor()
    
    let currentDataSource = vc.getCurrentDataSource()
    
    XCTAssertTrue(currentDataSource.testVariable == 30, "Test Variable should be 30 After")
  }
}
