//
//  FirstSceneSceneTests.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 10/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import SampleVIPSwift

struct FirstSceneInjectorTest: Injectable {
  static let shared: FirstSceneInjectorTest = FirstSceneInjectorTest()
  private init() {}
}

//use the factory Dependency injection and implement the factorable protocol
extension FirstSceneInjectorTest: FirstSceneFactorable, ServicesFactorable {
  
  func makeRouter(viewController: UIViewController?) -> FirstSceneRouting {
    let router = FirstSceneRouter(viewController)
    //custom implementation for this test
    return router
  }
  
}

class FirstSceneSceneTests: XCTestCase {
  
  var vc: FirstSceneViewController<FirstSceneInjectorTest>!
  var customDataSource: FirstSceneModel.DataSource!
  
  override func setUp() {
    
    customDataSource = FirstSceneModel.DataSource(testVariable: 29)
    let customView = FirstSceneView()
    
    vc = FirstSceneViewController(factory: FirstSceneInjectorTest.shared, mainView: customView, dataSource: customDataSource)
  }
  
  override func tearDown() { }
  
  func testCustomInteractorDataSourceShouldChange() {
    
    XCTAssertTrue(customDataSource.testVariable == 29, "Test Variable should be 29")
    
    vc.doSomethingToInteractor()
    
    let currentDataSource = vc.getCurrentDataSource()
    
    XCTAssertTrue(currentDataSource.testVariable == 30, "Test Variable should be 30 After")
  }
}
