//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import Foundation

struct ___VARIABLE_sceneName___Model {
    
    enum Request {
        case doSomething(_ item: Int)
    }
    
    enum Response {
        case doSomething(_ newItem: Int, _ isItem: Bool)
    }
    
    enum ViewModel {
        case doSomething(_ viewModelData: NSObject)
    }
    
    enum Route {
        case xScene(_ xData: Int)
    }
    
    struct DataSource: DataSourceable {
        //var test: Int
    }
}
