//
//  FirstSceneRouter.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 10/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstSceneRouting {
    
    func routeTo(_ route: FirstSceneModel.Route)
}

final class FirstSceneRouter: Routeable  {
    
    private weak var viewController: UIViewController?
    
    init(_ viewController: UIViewController?) {
        self.viewController = viewController
    }
}


//MARK: - FirstSceneRouting
extension FirstSceneRouter: FirstSceneRouting {

     func routeTo(_ route: FirstSceneModel.Route) {
        
        switch route {
            
        case .xScene(let data):
            showXSceneBy(data)
        }
        
        print("Show X Screen")
    }
}


//MARK: - Private Zone
private extension FirstSceneRouter {
    
    func showXSceneBy(_ data: Int) {
        print("will show the next screen")
    }
}
