//
//  FirstSceneModel.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 10/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import Foundation

struct FirstSceneModel {
    
    enum Requests {
        case doSomething(_ item: Int)
    }
    
    enum Responses {
        case doSomething(_ newItem: Int, _ isItem: Bool)
    }
    
    enum ViewModels {
        case doSomething(_ viewModelData: NSObject)
    }
    
    enum Routes {
        case xScene(_ xData: Int)
    }
    
    struct DataSource: DataSourceable {
        var testVariable: Int
    }
}
