//
//  FirstRouter.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 31/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstRouting {
    
    func routeTo(_ route: FirstModel.Route)
    func dismissFirstScene()
}

final class FirstRouter: Routeable  {
    
    private weak var viewController: UIViewController?
    
    init(_ viewController: UIViewController?) {
        self.viewController = viewController
    }
}


//MARK: - FirstRouting
extension FirstRouter: FirstRouting {

    func routeTo(_ route: FirstModel.Route) {

        switch route {
            
        case .xScene(let data):
            showXSceneBy(data)
        }
    }
  
    func dismissFirstScene() {
      viewController?.dismiss(animated: true)
    }
}


//MARK: - Private Zone
private extension FirstRouter {
    
    func showXSceneBy(_ data: Int) {
        print("will show the next screen")
    }
}
