//
//  FirstModel.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 31/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import Foundation

struct FirstModel {
    
    enum Request {
        case doSomething(_ item: Int)
    }
    
    enum Response {
        case doSomething(_ newItem: Int, _ isItem: Bool)
    }
    
    enum ViewModel {
        case doSomething(_ viewModelData: NSObject)
    }
    
    enum Route {
        case xScene(_ xData: Int)
    }
    
    struct DataSource: DataSourceable {
        var testVariable: Int
    }
}
