//
//  FirstPresenter.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 31/10/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol FirstPresentationLogic {
    func presentResponse(_ response: FirstModel.Response)
}

final class FirstPresenter: Presentable {
    private weak var viewController: FirstDisplayLogic?
    
    init(_ viewController: FirstDisplayLogic?) {
        self.viewController = viewController
    }
}


//MARK: - FirstPresentationLogic
extension FirstPresenter: FirstPresentationLogic {
    
    func presentResponse(_ response: FirstModel.Response) {
        
        switch response {
            
        case .doSomething(let newItem, let isItem):
            presentDoSomething(newItem, isItem)
        }
    }
}


//MARK: - Private Zone
private extension FirstPresenter {
    
    func presentDoSomething(_ newItem: Int, _ isItem: Bool) {
        
        //prepare data for display and send it further
        
        viewController?.displayViewModel(.doSomething(NSObject()))
    }
}
