//
//  LoginRouter.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 24/11/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRouting {
  
  func routeTo(_ route: LoginModel.Route)
}

final class LoginRouter: Routeable  {
  
  private weak var viewController: UIViewController?
  
  init(_ viewController: UIViewController?) {
    self.viewController = viewController
  }
}


//MARK: - LoginRouting
extension LoginRouter: LoginRouting {
  
  func routeTo(_ route: LoginModel.Route) {
    DispatchQueue.main.async {
      switch route {
        
      case .dismissLoginScene:
        self.dismissLoginScene()
        
      case .xScene(let data):
        self.showXSceneBy(data)
      }
    }
  }
}


//MARK: - Private Zone
private extension LoginRouter {
  
  func dismissLoginScene() {
    viewController?.dismiss(animated: true)
  }
  
  func showXSceneBy(_ data: Int) {
    print("will show the next screen")
  }
}
