//
//  LoginModel.swift
//  SampleVIPSwift
//
//  Created by Andrei Popilian on 24/11/2019.
//  Copyright (c) 2019 Andrei Popilian. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import Foundation

struct LoginModel {
  
  enum Request {
    case authenticate(withEmail: String, andPassword: String)
  }
  
  enum Response {
    case authenticate(withUserId: String)
  }
  
  enum ViewModel {
    case authenticate(withUserId: String)
  }
  
  enum Route {
    case dismissLoginScene
    case showAuthenticateSuccess(withUserId: String)
  }
  
  struct DataSource: DataSourceable {
    var userId: String?
  }
}
