//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import XCTest
@testable import ___PROJECTNAME___


final class ___VARIABLE_sceneName___RouterTests: XCTestCase {
  
  private var router: ___VARIABLE_sceneName___Router!
  private var viewController: ___VARIABLE_sceneName___ViewControllerSpy!

  override func setUp() {
    viewController = ___VARIABLE_sceneName___ViewControllerSpy()
    router = ___VARIABLE_sceneName___Router(viewController: viewController)
  }

  override func tearDown() {
    viewController = nil
    router = nil
  }
}


// MARK: - Tests
extension ___VARIABLE_sceneName___RouterTests {

  func textExample() {
  }
}


// MARK: - Spy Classes Setup
private extension ___VARIABLE_sceneName___RouterTests {

  final class ___VARIABLE_sceneName___ViewControllerSpy: UIViewController {
    var dismissExpectation: XCTestExpectation!
    var isDismissed: Bool = false

    override func dismiss(animated flag: Bool, completion: (() -> Void)? = nil) {
      isDismissed = true
      dismissExpectation.fulfill()
    }
  }
}
