//
//  Factorable.swift
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct AppInjector {}

protocol Injectable {}

protocol Factorable {

    associatedtype DisplayLogic
    associatedtype DataSource
    associatedtype Interactor
    associatedtype Presenter
    associatedtype Router

    func makeInteractor(viewController: DisplayLogic?, dataSource: DataSource) -> Interactor
    func makePresenter(_ viewController: DisplayLogic?) -> Presenter
    func makeRouter(viewController: UIViewController?) -> Router
}
